import { describe, expect, test } from "bun:test";
import { parseBun, parseNpm, parsePnpm, parseYarn } from "./lockfile";

describe("parseNpm (lockfileVersion 3)", () => {
  test("extracts name@version from packages map, skips root and links", () => {
    const text = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        "": { name: "myapp", version: "1.0.0" },
        "node_modules/lodash": { version: "4.17.21", resolved: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz" },
        "node_modules/@scope/foo": { version: "2.0.0" },
        "node_modules/local-link": { resolved: "../local", link: true, version: "0.0.0" },
        "node_modules/react": { version: "18.3.1" },
      },
    });
    const entries = parseNpm(text);
    expect(entries).toEqual([
      { name: "@scope/foo", version: "2.0.0" },
      {
        name: "lodash",
        version: "4.17.21",
        resolved: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
      },
      { name: "react", version: "18.3.1" },
    ]);
  });

  test("falls back to nested dependencies (lockfileVersion 1)", () => {
    const text = JSON.stringify({
      lockfileVersion: 1,
      dependencies: {
        lodash: { version: "4.17.21" },
        react: {
          version: "18.3.1",
          dependencies: { "loose-envify": { version: "1.4.0" } },
        },
      },
    });
    const entries = parseNpm(text);
    expect(entries).toEqual([
      { name: "lodash", version: "4.17.21" },
      { name: "loose-envify", version: "1.4.0" },
      { name: "react", version: "18.3.1" },
    ]);
  });
});

describe("parseBun (bun.lock text format)", () => {
  test("extracts name@version from packages array entries", () => {
    const text = `{
  "lockfileVersion": 1,
  "workspaces": { "": { "name": "app" } },
  "packages": {
    "@types/bun": ["@types/bun@1.3.14", "", { "dependencies": {} }, "sha512-x"],
    "@types/node": ["@types/node@25.9.1", "", {}, "sha512-y"],
    "lodash": ["lodash@4.17.21", "", {}, "sha512-z"],
  }
}`;
    const entries = parseBun(text);
    expect(entries).toEqual([
      { name: "@types/bun", version: "1.3.14" },
      { name: "@types/node", version: "25.9.1" },
      { name: "lodash", version: "4.17.21" },
    ]);
  });
});

describe("parsePnpm (pnpm-lock.yaml)", () => {
  test("extracts name@version from packages block, v6 format", () => {
    const text = `lockfileVersion: '6.0'

packages:

  /@scope/foo@1.0.0:
    resolution: {integrity: sha512-x}

  /lodash@4.17.21:
    resolution: {integrity: sha512-y}

snapshots: {}
`;
    const entries = parsePnpm(text);
    expect(entries).toEqual([
      { name: "@scope/foo", version: "1.0.0" },
      { name: "lodash", version: "4.17.21" },
    ]);
  });

  test("extracts name@version from packages block, v9 format without leading slash", () => {
    const text = `lockfileVersion: '9.0'

packages:

  '@scope/foo@1.0.0':
    resolution: {integrity: sha512-x}

  lodash@4.17.21:
    resolution: {integrity: sha512-y}
`;
    const entries = parsePnpm(text);
    expect(entries).toEqual([
      { name: "@scope/foo", version: "1.0.0" },
      { name: "lodash", version: "4.17.21" },
    ]);
  });
});

describe("parseYarn (yarn.lock v1)", () => {
  test("extracts name and version from block headers", () => {
    const text = `# THIS IS AN AUTOGENERATED FILE.

"@scope/foo@^1.0.0":
  version "1.0.5"
  resolved "https://registry.yarnpkg.com/x"

lodash@^4.17.0, lodash@^4.17.21:
  version "4.17.21"
  resolved "..."

react@18.3.1:
  version "18.3.1"
  resolved "..."
`;
    const entries = parseYarn(text);
    expect(entries).toEqual([
      { name: "@scope/foo", version: "1.0.5" },
      { name: "lodash", version: "4.17.21" },
      { name: "react", version: "18.3.1" },
    ]);
  });

  test("skips workspace/link/file/git protocols", () => {
    const text = `local-pkg@workspace:packages/foo:
  version: 0.0.0

git-pkg@git+https://example.com/x.git:
  version: 1.0.0

real@^1.0.0:
  version "1.2.3"
  resolved "..."
`;
    const entries = parseYarn(text);
    expect(entries).toEqual([{ name: "real", version: "1.2.3" }]);
  });
});
